using MediatR;

namespace Application.Contracts.Features.DispatchDocuments.Queries.GetDispatchDocumentNumbers;

public sealed record GetDispatchDocumentNumbersQuery(GetDispatchDocumentNumbersRequestDto Dto) : IRequest<GetDispatchDocumentNumbersResponseDto>;